- name: This playbook will install nginx web server, configure it and deploy web page in it.
  hosts: all
  vars_files:
    - nginx-variables.yml

  tasks:
    - include: "install-nginx-{{ansible_distribution|lower}}.yml"

    - include: start-nginx-service.yml

    - include: "configure-nginx-{{ansible_distribution|lower}}.yml"

    - include: update-document-root-folder.yml
    - include: deploy-custom-webpage.yml     

- name: Test the nginx deployments
  hosts: localhost
  tasks:
     - include: test-nginx-deployment.yml
